import { ArrowUpRight, Compass as Sparkles, Globe2 } from "lucide-react";
import React from "react";
import { Link } from "wouter";
import { BentoCard } from "@/components/sunex/BentoCard";
import { PageHero } from "@/components/sunex/PageHero";
import { Reveal } from "@/components/sunex/Reveal";

const team = [
  { name: "Sanjeeth Suresh", badge: "Founder", role: "Co-Founder", image: "/manus-storage/sanjeeth_420f591e.jpg", portraitClass: "team-card--sanjeeth", description: "Visionary leader responsible for defining the company’s direction, identifying new opportunities, and transforming ideas into successful business initiatives. Leads strategic planning and organizational growth." },
  { name: "Umesh H", badge: "Founder", role: "Co-Founder | Innovator | Product Visionary", image: "/manus-storage/umesh_1435ca88.jpg", portraitClass: "team-card--umesh", description: "Focused on envisioning what comes next and bringing it to life through strategic thinking, design excellence, and technological innovation. Committed to creating solutions that leave a lasting impact on people, communities, and the future." },
  { name: "Dr. Raghavendra Deshpande", badge: "Mentor", role: "Mentor", image: "/manus-storage/raghavendra_c05f2baa.jpg", portraitClass: "team-card--raghavendra", description: "Scientific lead and domain expert guiding the engineering design, research frameworks, and bio-mechanical innovation at the core of UrbanTree." },
];

export default function About() {
  return <>
    <PageHero eyebrow="01 / About SunEx" title={<>Innovation <em>with purpose.</em></>} image="/manus-storage/about-hero-bg_bd135a7e.jpg" description="SunEx Technologies develops sustainable environmental solutions, future-ready talent, and healthcare access with real-world impact." action={{ label: "Explore our work", href: "/product" }} />

    <section className="section content-wrap"><div className="page-copy-grid about-intro"><Reveal className="about-intro__copy"><div><p className="eyebrow">Our perspective</p><h2 className="display">Technology should<br />improve business <em>and improve lives.</em></h2><p className="copy">SunEx Technologies Pvt. Ltd. is an innovation-driven company committed to solving real-world challenges through technology and strategic partnerships.</p><p className="copy copy--small">Our focus lies in creating sustainable environmental solutions, developing future-ready talent through education, and enabling world-class healthcare access for international patients.</p></div></Reveal><Reveal delay={.12} className="image-panel image-panel--tall"><img src="/manus-storage/about-innovation_62dcd955.jpg" alt="SunEx innovation team" /><div className="image-panel__float image-panel__float--about"><small>Guiding principles</small><strong>Innovation, sustainability, and social impact.</strong></div></Reveal></div></section>

    <section className="section section--mist origin-section"><div className="content-wrap"><Reveal className="origin-section__heading"><div><p className="eyebrow">How the work begins</p><h2 className="display">Start with the reality.<br /><em>Build toward what is possible.</em></h2></div><p className="copy">SunEx brings environmental infrastructure, applied learning, and care-planning conversations into one practical question: what would make progress more useful for the people affected by it?</p></Reveal><div className="origin-section__steps">{[["01", "See the human condition", "Begin with the place, learner, patient, or organization that needs a clearer path forward."], ["02", "Connect the right capability", "Bring together practical technology, domain insight, and partners who can make the next step real."], ["03", "Build for the long term", "Shape systems intended to create durable environmental, economic, and social value."]].map(([number, title, text], index) => <Reveal className="origin-step" delay={index * .06} key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div><Reveal className="origin-section__note"><span>Timeline in progress</span><p>Company milestones, partner stories, and deployment history will be added here as dated, approved material becomes available.</p></Reveal></div></section>

    <section className="section section--mist"><div className="content-wrap"><Reveal className="split-heading"><div><p className="eyebrow">Vision & mission</p><h2 className="display">A direction that holds up <em>over time.</em></h2></div></Reveal><div className="two-up"><Reveal><BentoCard className="bento-card--pale" label="Vision"><Globe2 size={25} /><h3>Healthier communities. Smarter societies.</h3><p>To become a globally recognized innovation company delivering sustainable technologies and life-changing solutions that create healthier communities and smarter societies.</p></BentoCard></Reveal><Reveal delay={.1}><BentoCard className="bento-card--pale" label="Mission"><Sparkles size={25} /><h3>Technology for practical impact.</h3><p>To develop impactful technologies and services that address environmental challenges, empower individuals through education, and simplify access to world-class healthcare.</p></BentoCard></Reveal></div></div></section>

    <section className="section values-field-section"><div className="content-wrap"><Reveal className="values-field-hero"><div className="values-field-hero__media"><img src="/manus-storage/sunex-values-studio_3ad31d8d.jpg" alt="SunEx team shaping sustainable innovation together" /><div className="values-field-hero__veil" /><div className="values-field-hero__index"><span>01</span><i /> <small>The SunEx values field</small></div><div className="values-field-hero__caption"><small>Our common ground</small><strong>What guides the work<br />when no one is watching.</strong></div></div><div className="values-field-hero__copy"><div className="values-field-hero__label"><span><Sparkles size={15} /></span><p>Core values</p></div><p className="eyebrow eyebrow--orange">More than words on a wall</p><h2>Principles that<br /><em>shape the possible.</em></h2><p>SunEx is built on six values that travel together. They help us imagine responsibly, partner honestly, and leave people and places stronger than we found them.</p><div className="values-field-hero__compass"><span>01</span><i /><span>02</span><i /><span>03</span><small>Three commitments. Six values.</small></div></div></Reveal><div className="values-field-intro"><div><p className="eyebrow">The values field</p><h3>Every value has a<br /><em>partner in action.</em></h3></div><p>Our principles work as a system, not a checklist. Each pair creates a practical tension that improves both how we think and how we deliver.</p></div><div className="values-field-pairs">{[{ number: "01", theme: "Imagine", left: "Innovation", right: "Excellence", text: "We pursue what is next with the discipline to make it genuinely useful.", note: "New ideas, held to a higher bar." }, { number: "02", theme: "Earn", left: "Integrity", right: "People First", text: "We make clear choices, tell the truth, and keep the people affected by our work at the center.", note: "Trust built through every decision." }, { number: "03", theme: "Extend", left: "Sustainability", right: "Global Collaboration", text: "We design for the long term and build partnerships that allow practical impact to travel further.", note: "Local purpose. Shared progress." }].map((pair, index) => <Reveal className="values-field-pair" delay={index * .07} key={pair.number}><div className="values-field-pair__meta"><span>{pair.number}</span><p>{pair.theme}</p></div><div className="values-field-pair__values"><strong>{pair.left}</strong><i>+</i><strong>{pair.right}</strong></div><div className="values-field-pair__copy"><p>{pair.text}</p><span>{pair.note}</span></div></Reveal>)}</div></div></section>

    <section className="section section--mist"><div className="content-wrap"><div className="split-heading"><div><p className="eyebrow">Leadership</p><h2 className="display">Leaders who innovate.<br /><em>Leaders who transform.</em></h2></div><p className="copy">Each leader brings deep domain expertise and a proven track record.</p></div><div className="team-grid">{team.map((leader, index) => <Reveal className={`team-card ${leader.portraitClass}`} delay={index * .08} key={leader.name}><div className="team-card__media"><img src={leader.image} alt={leader.name} /></div><div className="team-card__body"><span>{leader.badge}</span><h3>{leader.name}</h3><p><strong>{leader.role}</strong><br />{leader.description}</p></div></Reveal>)}</div></div></section>

    <section className="section content-wrap"><Reveal className="large-cta"><p className="eyebrow">Work with SunEx</p><h2>Partner with us to build <em>what matters.</em></h2><p>Explore the products and capabilities designed to create more sustainable, skilled, and connected communities.</p><Link href="/contact" className="action-pill">Get in touch <span><ArrowUpRight size={16} /></span></Link></Reveal></section>
  </>;
}
