import { Link } from "wouter";
import React, { useState } from "react";
import { ArrowRight, ArrowUpRight, BadgeCheck, BriefcaseBusiness, GraduationCap } from "lucide-react";
import { PageHero } from "@/components/sunex/PageHero";
import { Reveal } from "@/components/sunex/Reveal";

const courseCatalog = [
  { title: "Responsible and Safe AI Systems", area: "AI & emerging technology", briefTitle: "Build responsible AI decisions.", description: "Explore responsible design and deployment considerations for modern AI systems.", dialogue: "Use this selection to discuss governance priorities, evaluation questions, and the kinds of AI decisions you want to examine.", themes: ["Governance", "Evaluation"], image: "/manus-storage/responsible-ai_f08891c8.jpg" },
  { title: "Agentic AI Intern & generative AI", area: "AI & emerging technology", briefTitle: "Plan intelligent workflows.", description: "Explore agent-led and generative AI workflows for changing technology environments.", dialogue: "Start the learning conversation with the workflow you want to improve, the human role you want to retain, and the outcomes that matter.", themes: ["Agent workflows", "Generative systems"], image: "/manus-storage/agentic-ai_b2999545.png" },
  { title: "LLM fine tuning", area: "AI & emerging technology", briefTitle: "Refine models for a focused task.", description: "Explore approaches to adapting and refining large language models for focused use cases.", dialogue: "Bring a use case, a domain question, or a data-curation interest to shape a more focused conversation with the learning team.", themes: ["Data curation", "Model adaptation"], image: "/manus-storage/llm-tuning_38979604.jpg" },
  { title: "Quantum computing", area: "AI & emerging technology", briefTitle: "Explore a new computing frontier.", description: "Explore foundational quantum-computing concepts and their place in future technology work.", dialogue: "Use the conversation to connect your current technical background with the quantum concepts and future-system questions you want to explore.", themes: ["Quantum foundations", "Future systems"], image: "/manus-storage/quantum_acd066e0.jpg" },
  { title: "AI for Electrical Power systems", area: "Energy systems", briefTitle: "Read energy systems with AI.", description: "Explore AI applications in electrical power systems and connected energy environments.", dialogue: "Discuss the energy environment you are interested in, the decisions that need better visibility, and how AI may support the conversation.", themes: ["Power analytics", "Connected energy"], image: "/manus-storage/ai-power_b71aa6be.jpg" },
  { title: "Industrial Programmable Logic Controllers", area: "Industrial automation", briefTitle: "Control systems in action.", description: "Explore programmable control foundations for industrial systems and operations.", dialogue: "Start with the industrial process or automation setting you want to understand, then map the control questions you want to work through.", themes: ["PLC logic", "Automation"], image: "/manus-storage/industrial-plc_13944bcb.jpg" },
  { title: "Battery management systems", area: "Energy systems", briefTitle: "Understand energy at cell level.", description: "Explore the systems thinking behind battery monitoring and management.", dialogue: "Frame the discussion around the energy-storage context, monitoring questions, or system trade-offs you want to investigate.", themes: ["Battery monitoring", "Energy storage"], image: "/manus-storage/battery-management_4c7944c2.jpg" },
  { title: "Industrial IOT", area: "Industrial automation", briefTitle: "Connect the industrial edge.", description: "Explore connected-device concepts for industrial operations and data-aware systems.", dialogue: "Bring the devices, signals, or operational questions that interest you to shape a practical connected-systems conversation.", themes: ["Sensors", "Edge systems"], image: "/manus-storage/industrial-iot_8d9a86f6.webp" },
  { title: "Cyber physical system Intern", area: "Connected systems", briefTitle: "Make software meet the real world.", description: "Explore the connection between physical processes, sensing, software, and systems engineering.", dialogue: "Use this course selection to discuss the physical process, software layer, and sensing challenge you want to connect.", themes: ["Sensing", "System integration"], image: "/manus-storage/cyber-physical_ca08a4b7.png" },
  { title: "Forward deployed engineering", area: "Applied engineering", briefTitle: "Take engineering into operation.", description: "Explore engineering patterns that take technical work into real operational environments.", dialogue: "Begin with the setting where engineering needs to work in practice, then discuss the constraints and decisions that make it real.", themes: ["Field delivery", "Applied problem solving"], image: "/manus-storage/forward-engineering_50edeae5.jpg" },
  { title: "Ethical Hacking & Cyber security", area: "Digital security", briefTitle: "Think like a defensive builder.", description: "Explore foundational ethical-hacking and cybersecurity concepts for modern technology systems.", dialogue: "Use the conversation to identify the systems you want to protect, the risks you want to recognise, and the defensive mindset you want to build.", themes: ["Security practice", "Threat awareness"], image: "/manus-storage/cybersecurity_9f1311f9.jpg" },
  { title: "Cloud computing", area: "Digital platforms", briefTitle: "Design for scalable platforms.", description: "Explore core cloud-computing foundations for scalable digital technology work.", dialogue: "Discuss the product, platform, or digital service context you care about, then focus the learning conversation on scale and reliability questions.", themes: ["Cloud foundations", "Platform thinking"], image: "/manus-storage/cloud-computing_58c80cbc.jpg" },
  { title: "Block chain", area: "Digital platforms", briefTitle: "Trace trust across a network.", description: "Explore distributed-ledger concepts and their role in connected digital systems.", dialogue: "Start with the trust, traceability, or coordination problem you want to explore before discussing distributed-ledger concepts.", themes: ["Distributed ledgers", "Network trust"], image: "/manus-storage/blockchain_4b0691fb.jpg" },
  { title: "Loop engineering, harness", area: "Applied engineering", briefTitle: "Turn precision into a system.", description: "Explore practical engineering foundations for structured electronic systems and harness work.", dialogue: "Use this selection to discuss the product context, precision work, and systems-assembly questions that you want to bring into focus.", themes: ["Harness design", "Systems assembly"], image: "/manus-storage/loop-harness_cc70f53f.jpeg" },
] as const;

const programmes = ["Industry Certification", "Professional Skills", "Technical Training", "Digital Skills", "AI & Emerging Tech", "Corporate Training", "Faculty Development", "Entrepreneurship", "Innovation Workshops", "Career Guidance"];

export default function Education() {
  const [activeCourse, setActiveCourse] = useState(0);

  return <>
    <PageHero eyebrow="03 / SkillConnect" title={<>Learning that becomes <em>opportunity.</em></>} image="/manus-storage/skillconnect-coding-lab_8415e96a.jpg" description="SkillConnect by SunEx Education connects industry-oriented training, certification, and hands-on skill development with the work that comes next." action={{ label: "Talk to our learning team", href: "/contact?interest=education" }} />

    <section className="section section--mist skillconnect-section"><div className="content-wrap">
      <Reveal className="skillconnect-intro"><div className="skillconnect-intro__copy"><div className="skillconnect-lockup" aria-label="SkillConnect by SunEx Education"><span className="skillconnect-lockup__icon"><GraduationCap size={17} /></span><div><strong>Skill<span>Connect</span></strong><small>by SunEx Education</small></div></div><p className="eyebrow eyebrow--orange">Learning that becomes opportunity</p><h2 className="display">The bridge between<br /><em>learning and work.</em></h2><p className="copy"><strong>SkillConnect by SunEx Education</strong> empowers students and professionals through industry-oriented training, certification, and hands-on skill development programs.</p><p className="copy copy--small">We partner with government institutions, universities, colleges, and private organizations to close the distance between education and employment.</p><Link href="/contact?interest=education" className="text-link">Explore SkillConnect <ArrowRight size={15} /></Link></div><div className="skillconnect-stage"><img src="/manus-storage/education_93e3980f.png" alt="SkillConnect applied learning session" /><div className="skillconnect-stage__overlay" /><div className="skillconnect-stage__badge"><GraduationCap size={20} /><div><small>SkillConnect pathway</small><strong>Learn. Apply. Advance.</strong></div></div><div className="skillconnect-stage__credit"><span>01</span><p>Industry-led<br />learning pathways</p></div></div></Reveal>
      <div className="skillconnect-metrics">{[{ value: "10+", label: "Learning offerings", Icon: GraduationCap }, { value: "2,500+", label: "Students trained", Icon: GraduationCap }, { value: "78%", label: "Placement rate", Icon: BriefcaseBusiness }, { value: "Gov + Private", label: "Institutional partners", Icon: BadgeCheck }].map(({ value, label, Icon }, index) => <Reveal className="skillconnect-metric" delay={index * .05} key={label}><Icon size={18} /><strong>{value}</strong><span>{label}</span></Reveal>)}</div>
      <Reveal className="skillconnect-programmes"><div><p className="eyebrow">Ways to learn</p><h3>Designed for the work<br /><em>that comes next.</em></h3></div><div className="skillconnect-programmes__tags">{programmes.map((programme) => <span className="skillconnect-tag" key={programme}>{programme}<ArrowUpRight size={13} /></span>)}</div></Reveal>
    </div></section>

    <section className="section course-showcase-section"><div className="content-wrap">
      <Reveal className="course-showcase-hero"><div className="course-showcase-hero__copy"><div className="skillconnect-lockup" aria-label="SkillConnect by SunEx Education"><span className="skillconnect-lockup__icon"><GraduationCap size={17} /></span><div><strong>Skill<span>Connect</span></strong><small>by SunEx Education</small></div></div><p className="eyebrow eyebrow--orange">Courses offered</p><h2 className="display">Choose a course<br /><em>built around your next step.</em></h2><p className="copy">Browse individual SkillConnect courses and focus the learning conversation on the technology work you want to explore.</p><div className="course-showcase-hero__facts"><div><strong>14</strong><span>Course offerings</span></div><div><strong>03</strong><span>Learning contexts</span></div><div><strong>01</strong><span>SkillConnect catalogue</span></div></div><Link href="/contact?interest=education" className="text-link">Talk to our learning team <ArrowRight size={15} /></Link></div><div className="course-showcase-photo"><img src="/manus-storage/skillconnect-editorial-studio_dd1b29e6.jpg" alt="SkillConnect learners collaborating in a technology studio" loading="lazy" /><div className="course-showcase-photo__shade" /><div className="course-showcase-photo__caption"><span>Applied learning</span><strong>From the studio to<br />the real world.</strong></div><div className="course-showcase-photo__index"><span>01</span><i /> <span>SkillConnect learning environment</span></div></div></Reveal>
      <div className="course-market-intro"><div><p className="eyebrow">Explore courses</p><h3>Pick the topic.<br /><em>See the learning focus.</em></h3></div><p>Course listings stay visible like a catalogue, while your selected course brings its learning focus and next action forward.</p></div>
      <Reveal className="course-market-feature course-market-feature--invitation"><div className="course-market-feature__media"><img src="/manus-storage/skillconnect-course-invitation_b174345c.jpg" alt="SkillConnect learners collaborating on engineering hardware" /><div><span>SkillConnect</span><strong>01</strong></div></div><div className="course-market-feature__copy"><p>For the curious, the makers, the doers</p><h3>Find the idea<br />you want to <em>build next.</em></h3><span className="course-market-feature__line" /><p className="course-market-feature__dialogue">Every course is a place to question, make, and move toward the kind of work you care about. Pick the topic that makes you want to keep learning.</p><div className="course-market-feature__meta"><span>Explore deeply</span><span>Apply confidently</span></div><Link href="/contact?interest=education" className="action-pill">Start your learning conversation <span><ArrowUpRight size={16} /></span></Link></div></Reveal>
      <div className="course-market-catalogue"><div className="course-market-catalogue__header"><div><span>Course index</span><strong>14 ways to focus your learning.</strong></div><p>Select a course to bring its learning brief forward.</p></div><div className="course-market-grid course-market-grid--catalogue">{courseCatalog.map((course, index) => <Reveal className="course-market-card-wrap" delay={(index % 3) * .05} key={course.title}><button type="button" className={`course-market-card course-market-card--catalogue course-market-card--tone-${(index % 4) + 1} ${activeCourse === index ? "is-active" : ""}`} onClick={() => setActiveCourse(index)} aria-label={`View ${course.title}`} aria-pressed={activeCourse === index}><div className="course-market-card__visual"><img src={course.image} alt="" loading="lazy" /><span>Course visual</span></div><div className="course-market-card__number">{String(index + 1).padStart(2, "0")}</div><div className="course-market-card__copy"><span>{course.area}</span><h3>{course.title}</h3><p>{course.description}</p></div><div className="course-market-card__action"><span>View learning brief</span><ArrowUpRight size={15} /></div></button></Reveal>)}</div></div>
    </div></section>

    <section className="section section--mist"><div className="content-wrap"><Reveal className="split-heading"><div><p className="eyebrow">Programme benefits</p><h2 className="display">Learning that travels<br /><em>into the real world.</em></h2></div></Reveal><div className="values-grid">{["Industry-Aligned Curriculum", "Expert Trainers", "Hands-on Learning", "Internship Opportunities", "Placement Assistance", "Recognized Certifications"].map((benefit, index) => <Reveal className="value-card" delay={(index % 3) * .05} key={benefit}><span>Benefit {String(index + 1).padStart(2, "0")}</span><strong>{benefit}</strong></Reveal>)}</div></div></section>
    <section className="section content-wrap"><Reveal className="large-cta"><p className="eyebrow">Build your next step</p><h2>Plan a learning pathway<br /><em>around your ambition.</em></h2><p>Talk with the SkillConnect team about courses, institutional training, and industry-aligned capability building.</p><Link href="/contact?interest=education" className="action-pill">Talk to our learning team <span><ArrowUpRight size={16} /></span></Link></Reveal></section>
  </>;
}
