import { Link } from "wouter";
import React, { useState } from "react";
import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpenCheck, BriefcaseBusiness, Building2, Compass, Cpu, GraduationCap, Handshake, Lightbulb, MessagesSquare, Presentation, School, UserRound, Wrench } from "lucide-react";
import "./EducationFocus.css";
import "./EducationAudience.css";
import "./EducationMetrics.css";
import { PageHero } from "@/components/sunex/PageHero";
import { Reveal } from "@/components/sunex/Reveal";

const courseCatalog = [
  { title: "Responsible and Safe AI Systems", area: "AI & emerging technology", briefTitle: "Build responsible AI decisions.", description: "Explore responsible design and deployment considerations for modern AI systems.", dialogue: "Use this selection to discuss governance priorities, evaluation questions, and the kinds of AI decisions you want to examine.", themes: ["Governance", "Evaluation"], image: "/manus-storage/responsible-ai_f08891c8.jpg" },
  { title: "Agentic AI Intern & generative AI", area: "AI & emerging technology", briefTitle: "Plan intelligent workflows.", description: "Explore agent-led and generative AI workflows for changing technology environments.", dialogue: "Start the learning conversation with the workflow you want to improve, the human role you want to retain, and the outcomes that matter.", themes: ["Agent workflows", "Generative systems"], image: "/manus-storage/agentic-ai_b2999545.png" },
  { title: "LLM fine tuning", area: "AI & emerging technology", briefTitle: "Refine models for a focused task.", description: "Explore approaches to adapting and refining large language models for focused use cases.", dialogue: "Bring a use case, a domain question, or a data-curation interest to shape a more focused conversation with the learning team.", themes: ["Data curation", "Model adaptation"], image: "/manus-storage/llm-tuning_38979604.jpg" },
  { title: "Quantum computing", area: "AI & emerging technology", briefTitle: "Explore a new computing frontier.", description: "Explore foundational quantum-computing concepts and their place in future technology work.", dialogue: "Use the conversation to connect your current technical background with the quantum concepts and future-system questions you want to explore.", themes: ["Quantum foundations", "Future systems"], image: "/manus-storage/quantum_acd066e0.jpg" },
  { title: "AI for Electrical Power systems", area: "Energy systems", briefTitle: "Read energy systems with AI.", description: "Explore AI applications in electrical power systems and connected energy environments.", dialogue: "Discuss the energy environment you are interested in, the decisions that need better visibility, and how AI may support the conversation.", themes: ["Power analytics", "Connected energy"], image: "/manus-storage/ai-power_b71aa6be.jpg" },
  { title: "Industrial Programmable Logic Controllers", area: "Industrial automation", briefTitle: "Control systems in action.", description: "Explore programmable control foundations for industrial systems and operations.", dialogue: "Start with the industrial process or automation setting you want to understand, then map the control questions you want to work through.", themes: ["PLC logic", "Automation"], image: "/manus-storage/industrial-plc_13944bcb.jpg" },
  { title: "Battery management systems", area: "Energy systems", briefTitle: "Understand energy at cell level.", description: "Explore the systems thinking behind battery monitoring and management.", dialogue: "Frame the discussion around the energy-storage context, monitoring questions, or system trade-offs you want to investigate.", themes: ["Battery monitoring", "Energy storage"], image: "/manus-storage/battery-management_4c7944c2.jpg" },
  { title: "Industrial IOT", area: "Industrial automation", briefTitle: "Connect the industrial edge.", description: "Explore connected-device concepts for industrial operations and data-aware systems.", dialogue: "Bring the devices, signals, or operational questions that interest you to shape a practical connected-systems conversation.", themes: ["Sensors", "Edge systems"], image: "/manus-storage/industrial-iot_8d9a86f6.webp" },
  { title: "Cyber physical system Intern", area: "Connected systems", briefTitle: "Make software meet the real world.", description: "Explore the connection between physical processes, sensing, software, and systems engineering.", dialogue: "Use this course selection to discuss the physical process, software layer, and sensing challenge you want to connect.", themes: ["Sensing", "System integration"], image: "/manus-storage/cyber-physical_ca08a4b7.png" },
  { title: "Forward deployed engineering", area: "Applied engineering", briefTitle: "Take engineering into operation.", description: "Explore engineering patterns that take technical work into real operational environments.", dialogue: "Begin with the setting where engineering needs to work in practice, then discuss the constraints and decisions that make it real.", themes: ["Field delivery", "Applied problem solving"], image: "/manus-storage/forward-engineering_50edeae5.jpg" },
  { title: "Ethical Hacking & Cyber security", area: "Digital security", briefTitle: "Think like a defensive builder.", description: "Explore foundational ethical-hacking and cybersecurity concepts for modern technology systems.", dialogue: "Use the conversation to identify the systems you want to protect, the risks you want to recognise, and the defensive mindset you want to build.", themes: ["Security practice", "Threat awareness"], image: "/manus-storage/cybersecurity_9f1311f9.jpg" },
  { title: "Cloud computing", area: "Digital platforms", briefTitle: "Design for scalable platforms.", description: "Explore core cloud-computing foundations for scalable digital technology work.", dialogue: "Discuss the product, platform, or digital service context you care about, then focus the learning conversation on scale and reliability questions.", themes: ["Cloud foundations", "Platform thinking"], image: "/manus-storage/cloud-computing_58c80cbc.jpg" },
  { title: "Block chain", area: "Digital platforms", briefTitle: "Trace trust across a network.", description: "Explore distributed-ledger concepts and their role in connected digital systems.", dialogue: "Start with the trust, traceability, or coordination problem you want to explore before discussing distributed-ledger concepts.", themes: ["Distributed ledgers", "Network trust"], image: "/manus-storage/blockchain_4b0691fb.jpg" },
  { title: "Loop engineering, harness", area: "Applied engineering", briefTitle: "Turn precision into a system.", description: "Explore practical engineering foundations for structured electronic systems and harness work.", dialogue: "Use this selection to discuss the product context, precision work, and systems-assembly questions that you want to bring into focus.", themes: ["Harness design", "Systems assembly"], image: "/manus-storage/loop-harness_cc70f53f.jpeg" },
] as const;

const skillConnectHeroImages = [
  "/images/skillconnect-celebration.jpg",
  "/images/skillconnect-professional.jpg",
  "/images/skillconnect-collaboration.jpg",
] as const;

const educationFocusAreas = [
  { title: "Skill Development", description: "Practical learning programs designed to build relevant skills, applied knowledge and career-ready capabilities through hands-on learning and real-world applications.", Icon: Wrench },
  { title: "Technology Education", description: "Hands-on exposure to emerging technologies, modern tools and evolving technology practices, guided by industry professionals and practitioners.", Icon: Cpu },
  { title: "Industry Readiness", description: "Helping learners understand workplace expectations, industry practices, professional skills and real-world applications to become job-ready.", Icon: BriefcaseBusiness },
  { title: "Workshops & Training", description: "Delivering practical workshops, expert-led training programs and technology bootcamps designed around current industry needs and emerging technologies.", Icon: BookOpenCheck },
  { title: "Innovation & Entrepreneurship", description: "Encouraging learners to explore ideas, solve real-world problems and develop innovative solutions through collaborative and experiential learning.", Icon: Lightbulb },
  { title: "Institutional Collaboration", description: "Partnering with schools, colleges, universities and educational institutions to design and deliver industry-oriented training programs, internships, skill development initiatives and academic collaborations.", Icon: Handshake },
] as const;

const institutionInitiatives = [
  { label: "Skill development", Icon: Wrench },
  { label: "Technology workshops", Icon: Presentation },
  { label: "Industry interaction", Icon: MessagesSquare },
  { label: "Training programs", Icon: BookOpenCheck },
  { label: "Innovation initiatives", Icon: Lightbulb },
  { label: "Career readiness", Icon: Compass },
  { label: "Technology awareness", Icon: Cpu },
  { label: "Industry oriented programs", Icon: Building2 },
] as const;
const studentBenefits = ["Develop practical skills", "Understand emerging technologies", "Gain industry exposure", "Explore career opportunities", "Build problem solving capabilities", "Develop innovation mindset", "Understand real world applications"] as const;

export default function Education() {
  const [activeCourse, setActiveCourse] = useState(0);

  return <>
    <PageHero eyebrow="Skill Connect by sunex technology" title={<>Preparing People for What Comes Next</>} image={skillConnectHeroImages[0]} backgroundImages={skillConnectHeroImages} description="We create learning opportunities that help students, professionals, job seekers and organisations build relevant capabilities, gain practical experience and stay prepared for the future" action={{ label: "Talk to our learning team", href: "/contact?interest=education" }} />

    <section className="section section--mist skillconnect-section"><div className="content-wrap">
      <Reveal className="skillconnect-intro skillconnect-intro--editorial"><div className="skillconnect-intro__lead"><p className="eyebrow eyebrow--orange">SkillConnect by SunEx Education</p><h2 className="display">The bridge between<br /><em>learning and work.</em></h2></div><div className="skillconnect-intro__copy"><p className="copy">Skill Connect by SunEx bridges the gap between academic education and industry requirements through practical learning, technology exposure and skill development.</p><p className="copy copy--small">Our programs are designed and delivered by industry experts, supported by a passionate team of young professionals and experienced mentors with over two decades of industry experience, bringing together fresh perspectives and real-world expertise</p><Link href="/contact?interest=education" className="text-link">Explore SkillConnect <ArrowRight size={15} /></Link></div></Reveal>
      <div className="skillconnect-metrics">{[{ value: "15+", label: "Learning Opportunities", Icon: GraduationCap }, { value: "10K", label: "Students trained", Icon: GraduationCap }, { value: "20+", label: "Industry professionals", Icon: BriefcaseBusiness }, { value: "Gov + Private", label: "Institutional partners", Icon: BadgeCheck }].map(({ value, label, Icon }, index) => <Reveal className="skillconnect-metric" delay={index * .05} key={label}><Icon size={18} /><strong>{value}</strong><span>{label}</span></Reveal>)}</div>
    </div></section>

    <section className="section education-approach-section" aria-labelledby="education-approach-title"><div className="content-wrap"><Reveal className="education-approach"><div><p className="eyebrow">Our approach</p><h2 id="education-approach-title">Learning beyond<br /><em>the classroom.</em></h2></div><div className="education-approach__content"><p>We believe effective education goes beyond theoretical knowledge. It should help learners understand, apply and continuously improve what they learn.</p><p className="education-approach__lead">Our approach combines:</p><div className="education-approach__pathway" aria-label="Education approach"><span>Knowledge</span><i>•</i><span>Practical Skills</span><i>•</i><span>Technology Exposure</span><i>•</i><span>Industry Relevance</span><i>•</i><span>Continuous Learning</span></div><p>Every learning experience is designed to combine academic concepts with hands-on practice, industry insights and mentorship from experienced professionals.</p><p>Through this approach, we help learners develop the confidence, competence and practical capabilities needed to adapt to evolving technologies and future career opportunities.</p></div></Reveal></div></section>

    <section className="section education-focus-section" aria-labelledby="education-focus-title"><div className="content-wrap"><div className="education-focus-layout education-focus-layout--balanced"><div className="education-focus-manifesto education-focus-manifesto--compact"><div className="education-focus-manifesto__content"><p className="eyebrow">What we focus on</p><h2 id="education-focus-title">Learning that builds<br /><em>real-world capability.</em></h2><span className="education-focus-manifesto__range" aria-hidden="true">01 — 06</span></div></div><div className="education-focus-grid">{educationFocusAreas.map(({ title, description, Icon }, index) => <Reveal className="education-focus-card" delay={(index % 3) * .05} key={title}><div className="education-focus-card__meta"><span className="education-focus-card__index">{String(index + 1).padStart(2, "0")}</span><span className="education-focus-card__icon"><Icon size={20} /></span></div><div className="education-focus-card__copy"><h3>{title}</h3><p>{description}</p></div></Reveal>)}</div></div></div></section>

    <section className="section education-institutions-section" aria-labelledby="institutions-title"><div className="content-wrap"><Reveal className="education-audience education-audience--dark"><div className="education-audience__heading"><span className="education-audience__icon"><School size={23} /></span><p className="eyebrow">For educational institutions</p><h2 id="institutions-title">Partnerships that make<br /><em>learning more relevant.</em></h2><p>We collaborate with educational institutions on relevant initiatives including:</p><Link href="/contact?interest=partnership" className="rivr-pill education-audience__action">Partner with SunEx <span><ArrowUpRight size={16} /></span></Link></div><ul className="education-audience__list education-audience__list--initiatives">{institutionInitiatives.map(({ label, Icon }, index) => <li key={label}><span className="education-audience__list-icon"><Icon size={17} /></span><strong>{label}</strong><small>{String(index + 1).padStart(2, "0")}</small></li>)}</ul></Reveal></div></section>

    <section className="section education-students-section" aria-labelledby="students-title"><div className="content-wrap"><Reveal className="education-audience education-audience--light"><div className="education-audience__heading"><span className="education-audience__icon"><UserRound size={23} /></span><p className="eyebrow eyebrow--orange">For students</p><h2 id="students-title">Confidence for the<br /><em>real world.</em></h2><p>Our initiatives can help students:</p></div><ul className="education-audience__list">{studentBenefits.map((benefit, index) => <li key={benefit}><span>{String(index + 1).padStart(2, "0")}</span>{benefit}</li>)}</ul></Reveal></div></section>

    <section className="section education-goal-section" aria-labelledby="education-goal-title"><div className="content-wrap"><Reveal className="education-goal"><p className="eyebrow">Our goal</p><h2 id="education-goal-title">Make learning more relevant.<br /><em>Make skills more practical.</em></h2><p>We want to contribute to an education ecosystem where learners are better prepared for the opportunities and challenges of tomorrow.</p><Link href="/contact?interest=education" className="rivr-pill education-goal__action">Explore our education initiatives <span><ArrowUpRight size={16} /></span></Link></Reveal></div></section>

    <section className="section course-showcase-section"><div className="content-wrap">
      <Reveal className="course-showcase-hero"><div className="course-showcase-hero__copy"><div className="skillconnect-lockup" aria-label="SkillConnect by SunEx Education"><span className="skillconnect-lockup__icon"><GraduationCap size={17} /></span><div><strong>Skill<span>Connect</span></strong><small>by SunEx Education</small></div></div><p className="eyebrow eyebrow--orange">Courses offered</p><h2 className="display">Choose a course<br /><em>built around your next step.</em></h2><p className="copy">Browse individual SkillConnect courses and focus the learning conversation on the technology work you want to explore.</p><div className="course-showcase-hero__facts"><div><strong>14</strong><span>Course offerings</span></div><div><strong>03</strong><span>Learning contexts</span></div><div><strong>01</strong><span>SkillConnect catalogue</span></div></div><Link href="/contact?interest=education" className="text-link">Talk to our learning team <ArrowRight size={15} /></Link></div><div className="course-showcase-photo"><img src="/manus-storage/skillconnect-editorial-studio_dd1b29e6.jpg" alt="SkillConnect learners collaborating in a technology studio" loading="lazy" /><div className="course-showcase-photo__shade" /><div className="course-showcase-photo__caption"><span>Applied learning</span><strong>From the studio to<br />the real world.</strong></div><div className="course-showcase-photo__index"><span>01</span><i /> <span>SkillConnect learning environment</span></div></div></Reveal>
      <div className="course-market-intro"><div><p className="eyebrow">Explore courses</p><h3>Pick the topic.<br /><em>See the learning focus.</em></h3></div><p>Course listings stay visible like a catalogue, while your selected course brings its learning focus and next action forward.</p></div>
      <Reveal className="course-market-feature course-market-feature--invitation"><div className="course-market-feature__media"><img src="/manus-storage/skillconnect-course-invitation_b174345c.jpg" alt="SkillConnect learners collaborating on engineering hardware" /><div><span>SkillConnect</span><strong>01</strong></div></div><div className="course-market-feature__copy"><p>For the curious, the makers, the doers</p><h3>Find the idea<br />you want to <em>build next.</em></h3><span className="course-market-feature__line" /><p className="course-market-feature__dialogue">Every course is a place to question, make, and move toward the kind of work you care about. Pick the topic that makes you want to keep learning.</p><div className="course-market-feature__meta"><span>Explore deeply</span><span>Apply confidently</span></div><Link href="/contact?interest=education" className="rivr-pill">Start your learning conversation <span><ArrowUpRight size={16} /></span></Link></div></Reveal>
      <div className="course-market-catalogue"><div className="course-market-catalogue__header"><div><span>Course index</span><strong>14 ways to focus your learning.</strong></div><p>Select a course to bring its learning brief forward.</p></div><div className="course-market-grid course-market-grid--catalogue">{courseCatalog.map((course, index) => <Reveal className="course-market-card-wrap" delay={(index % 3) * .05} key={course.title}><button type="button" className={`course-market-card course-market-card--catalogue course-market-card--tone-${(index % 4) + 1} ${activeCourse === index ? "is-active" : ""}`} onClick={() => setActiveCourse(index)} aria-label={`View ${course.title}`} aria-pressed={activeCourse === index}><div className="course-market-card__visual"><img src={course.image} alt="" loading="lazy" /><span>Course visual</span></div><div className="course-market-card__number">{String(index + 1).padStart(2, "0")}</div><div className="course-market-card__copy"><span>{course.area}</span><h3>{course.title}</h3><p>{course.description}</p></div><div className="course-market-card__action"><span>View learning brief</span><ArrowUpRight size={15} /></div></button></Reveal>)}</div></div>
    </div></section>

    <section className="section content-wrap"><Reveal className="large-cta"><p className="eyebrow">Build your next step</p><h2>Plan a learning pathway<br /><em>around your ambition.</em></h2><p>Talk with the SkillConnect team about courses, institutional training, and industry-aligned capability building.</p><Link href="/contact?interest=education" className="rivr-pill">Talk to our learning team <span><ArrowUpRight size={16} /></span></Link></Reveal></section>
  </>;
}
