import React from "react";
import { ArrowUpRight, ChevronDown } from "lucide-react";
import { Link } from "wouter";
import { Reveal } from "@/components/sunex/Reveal";

const faqGroups = [
  { label: "About SunEx", href: "/contact?interest=partnership", prompt: "Understand SunEx", questions: [{ question: "What is SunEx Technologies?", answer: "SunEx Technologies is a technology and innovation driven organisation working across Education, Technology, Innovative Projects, Environmental Sustainability and Healthcare." }, { question: "What are SunEx's main areas of work?", answer: "Our core verticals are Education, Technology, Innovative Projects and Healthcare." }] },
  { label: "Projects & sustainability", href: "/contact?interest=urbantree", prompt: "Discuss a project", questions: [{ question: "Does SunEx develop its own projects?", answer: "Yes. SunEx develops and works on innovative projects designed to address real world challenges. UrbanTree is one of our existing projects." }] },
  { label: "Education", href: "/contact?interest=education", prompt: "Explore an area", questions: [{ question: "Does SunEx work in education?", answer: "Yes. Education is one of our core verticals. Our initiatives focus on practical learning, skill development, technology exposure and industry oriented capabilities." }] },
  { label: "Partnerships", href: "/contact?interest=partnership", prompt: "Start a conversation", questions: [{ question: "Who can work with SunEx?", answer: "We can collaborate with businesses, government institutions, educational institutions, healthcare organisations, technology partners, startups, innovators and communities." }, { question: "Can organisations partner with SunEx?", answer: "Yes. We welcome relevant opportunities for technology projects, education initiatives, innovation, sustainability, healthcare and strategic collaboration." }, { question: "How can I contact SunEx?", answer: "You can reach our team through the Contact Us page for business enquiries, partnerships, projects, institutional collaborations and other opportunities." }] },
] as const;

export default function Faq() { return <><section className="section faq-hero"><div className="content-wrap"><Reveal><p className="eyebrow">Frequently asked questions</p><h1>Answers for the<br /><em>next good question.</em></h1><p>Browse practical starting points about SunEx, its focus areas, projects, education, healthcare and collaboration. If the answer you need is not here, start a conversation.</p></Reveal></div></section><section className="section section--mist faq-section"><div className="content-wrap"><div className="faq-section__intro"><div><p className="eyebrow">Browse by topic</p><h2 className="display">Find the context.<br /><em>Choose the conversation.</em></h2></div><p className="copy">Each topic keeps the next action close to the question, so you can move from an answer to the right SunEx team without losing your place.</p></div><div className="faq-groups">{faqGroups.map((group, index) => <Reveal className="faq-group" delay={index * .05} key={group.label}><div className="faq-group__heading"><span>{String(index + 1).padStart(2, "0")}</span><div><p>{group.label}</p><h3>{group.prompt}</h3></div><Link href={group.href}>Talk to the team <ArrowUpRight size={15} /></Link></div><div className="faq-group__items">{group.questions.map((item) => <details key={item.question}><summary>{item.question}<ChevronDown size={18} /></summary><p>{item.answer}</p></details>)}</div></Reveal>)}</div><Reveal className="faq-escalation"><div><p className="eyebrow">Have an idea, challenge or project?</p><h3>Let's Build the<br /><em>Future Together.</em></h3></div><p>Whether you are looking to solve a technology challenge, develop an innovative project, build future ready skills, explore a sustainability initiative or collaborate on healthcare innovation, we would like to hear from you.</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: '15px', marginTop: '30px' }}><Link href="/contact" className="rivr-pill">Start a Conversation <span><ArrowUpRight size={16} /></span></Link><Link href="/product" className="rivr-pill" style={{ backgroundColor: 'transparent', color: 'var(--foreground)', border: '1px solid rgba(25, 55, 95, 0.2)' }}>Explore Our Projects <span><ArrowUpRight size={16} /></span></Link></div></Reveal></div></section></>; }
